import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '90%',
    height: 'auto',
    backgroundColor: '#03A66A',
    marginTop: 25,
    borderRadius: 15,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'space-evenly',
    flexDirection: 'column',
    padding: 10,
  },
  dadosInput: {
    width: '100%',
    height: 50,
    borderRadius: 10,
    backgroundColor: '#fff',
    padding: 15,
    color: '#202022',
    fontWeight: 'bold',
    fontSize: 16,
    marginVertical: 10,
    elevation: 3,
    borderWidth: 0.5,
    borderColor: '#65A693',
  },
  containerDescricao: {
    width: '100%',
    alignItems: 'flex-start',
    paddingLeft: 10,
  },
  descricaoDados: {
    color: '#fff',
    fontWeight: 'bold',
    fontVariant: ['small-caps'],
    textAlign: 'left',
  },
  containerButton: {
    width: 150, 
    height: 50,
    backgroundColor: '#8CBF1F',
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
  },
  textoButton: {
    color: '#F2F2F2',
    fontWeight: 'bold',
    fontSize: 16,
  },
});